#################################################################
#								#
#		Assignment 2 -HY345 				#
#		Makefile					#
#		Giorgos Geramoutsos @csd3927			#						
#								#
#################################################################

all:
	@echo "\nCompiling Study Room"
	gcc -g -pthread studyRoom.c -o studyRoom	
	@echo "Compilation Finished\n./studyRoom\n"
	
run:
	@echo "\nExecuting studyRoom\n"
	./studyRoom 
	@echo "Execution Finished"
	@echo "\n"

clean:	
	@echo "\nDeleting executable"
	rm -rf studyRoom
	@echo "Deleted\n"
